description: same as `BASEv4.yaml` with `num_expert_episodes=200` and `dropout=0.1` and `dagger_episodes=100`

base_config: ../BASEv4.yaml

overrides:
  dropout: 0.1
  num_expert_episodes: 200
  dagger_episodes: 100

global_seeds:
  - 0
  - 420
  - 5693
