
# observation / action schema
OBS_DIMS = 45
ACTION_DIMS = 8

# loss weights
GRIPPER_LOSS_WEIGHT=0.5
JOINTS_LOSS_WEIGHT=0.5

# epsilon
EPSILON = 1e-6

# rollout safety
MAX_ARM_DELTA = 1.2

# task metrics
CUBE_LIFT_MIN_DELTA = 0.05
# TRAY_PLACE_TOL = 0.08
TRAY_PLACE_TOL = 0.04
GRASP_STABLE_STEPS = 5
LOWERING_STABLE_STEPS = 5
RELEASE_STABLE_STEPS = 5
PLACEMENT_STABLE_STEPS = 50
PLACEMENT_MAX_SPEED = 0.05
PLACEMENT_Z_TOL = 0.04
RETREAT_STABLE_STEPS = 15
RETREAT_MIN_HEIGHT = 0.09
TRAY_INNER_XY_TOL = 0.05
